### ISSUE TITLE
SQL Error : Chat plugins

### ISSUE THREAD

**Issue by spychoux** [kanboard/plugin-chat#3]
Hi,

I have this error when I try to use the chat plugins : 

`
[2017-05-12 21:25:27] [critical] Chat: SQL error: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "chat_messages" does not exist
LINE 1: SELECT "id" FROM "chat_messages"     ORDER BY "id" DESC  LIM...
`

And I don't see the plugins windows on the browser. Anybody have this error or It's my configuration ;).

My configuration : 

* Application version: 1.0.43
* PHP version: 7.0.8
* PHP SAPI: fpm-fcgi
* OS version: OpenBSD 6.0
* Database driver: postgres
* Database version: 9.5.3
* Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0

Best regards.

**Comment by fguillot** [comment]
You should check your installation because SQL migrations are not executed.

**Comment by spychoux** [comment]
Hi,

I fix my problem, I create manually each table need for chat plugins and after all is correct. I don't understand why not created automatically ? Sure config.php problem ;).

Bye
